$('#submit-btn').click(function() {
  event.preventDefault()
  var city = $('#city-type').val()
  if (city === 'nyc' || city === 'new york city' || city === 'new york')
  $('body').css('background-image', 'url(images/nyc.jpg)' )
  if (city === 'austin' )
  $('body').css('background-image', 'url(images/austin.jpg)' )
  if (city === 'sf' || city === 'san francisco' )
  $('body').css('background-image', 'url(images/sf.jpg)' )
  if (city === 'la' || city === 'los angeles')
  $('body').css('background-image', 'url(images/la.jpg)' )
  if (city === 'sydney' )
  $('body').css('background-image', 'url(images/sydney.jpg)' )
})
